---
version: 2

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

before:
  hooks:
    - go mod tidy

builds:
  - binary: rvz
    main: ./cmd/rvz/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native
