---
name: Build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  golang-checks:
    name: Golang checks
    uses: bodgit/workflows/.github/workflows/golang-checks.yml@f2ad91a9e0ba58982cdc180b62f69555ddf17d06 # v1.0.0
    with:
      go_test_args: -v -short
